chore: Uninstall adobe-reader-11
Have to uninstall this, or I'll run into the following errors upon
`pacman -Syu`:

```
warning: cannot resolve "libffi=3.4.6", a dependency of "lib32-libffi"
:: The following package cannot be upgraded due to unresolvable dependencies:
      lib32-libffi

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libffi (3.4.5-1) breaks dependency 'libffi=3.4.4' required by lib32-libffi
```